#!/bin/bash
# author: Alex Byrne - ab63@sanger.ac.uk
# version 1.0.4

set -e

# source subcommands
source "${0%/*}"/subcommands/filter_subcommand.sh
source "${0%/*}"/subcommands/get_subcommand.sh

usage() {
	cat "${0%/*}"/doc/man_vcfilter >&2
	exit 1
}

# let first positional parameter be a 'subcommand'
# assign CLA, $@, to array called 'args' (excluding subcommand name by shifting it)
# use args array to pass command line arguments to subcommands
subcommand=$1
case $subcommand in
	filter)
		shift
		args=("$@")
		sub_filter
		;;
	get)
		shift
		args=("$@")
		sub_get
		;;
	expression)
		less "${0%/*}"/doc/man_expression
		exit 1
		;;
	help)
		usage
		;;
	version)
		echo "vcfilter version 1.0.4"
		;;
	*)
		echo "Error: Unrecognised subcommand: $1" >&2
		usage
		;;
esac

exit 0